### ISSUE TITLE
missing dependency on "thin"?

### ISSUE THREAD

**Issue by ktarplee** [denniskuczynski/beanstalkd_view#29]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- thin (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/backports-3.6.5/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/handler/thin.rb:1:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:295:in `setup_rack_handler'
	from /var/lib/gems/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:36:in `initialize'
	from /var/lib/gems/1.9.1/gems/beanstalkd_view-2.0.0/bin/beanstalkd_view:15:in `new'
	from /var/lib/gems/1.9.1/gems/beanstalkd_view-2.0.0/bin/beanstalkd_view:15:in `<top (required)>'
	from /usr/local/bin/beanstalkd_view:23:in `load'
	from /usr/local/bin/beanstalkd_view:23:in `<main>'

After gem installing I got the above error when trying to run it.  I installed "thin" via gem and it fixed the problem but this means there is a dependency missing in your project or one you depend on.

**Comment by ronail** [comment]
I am facing the same issue. Any update?

**Comment by denniskuczynski** [comment]
The executable currently uses the [vegas](http://code.quirkey.com/vegas/) gem which defaults to use the locally installed `thin` since no rack handler is specified.

I should update the docs to mention that you must also `gem install thin` if you want to use the executable.

**Comment by denniskuczynski** [comment]
You can also specify the handler with the -s option:
```
$ beanstalkd_view -h

Vegas options:
  -K, --kill               kill the running process and exit
  -S, --status             display the current running PID and URL then quit
  -s, --server SERVER      serve using SERVER (thin/mongrel/webrick)
  -o, --host HOST          listen on HOST (default: 0.0.0.0)
  -p, --port PORT          use PORT (default: 5678)
  -x, --no-proxy           ignore env proxy settings (e.g. http_proxy)
  -e, --env ENVIRONMENT    use ENVIRONMENT for defaults (default: development)
  -F, --foreground         don't daemonize, run in the foreground
  -L, --no-launch          don't launch the browser
  -d, --debug              raise the log level to :debug (default: :info)
      --app-dir APP_DIR    set the app dir where files are stored (default: ~/.vegas/Beanstalkd_View)/)
  -P, --pid-file PID_FILE  set the path to the pid file (default: app_dir/Beanstalkd_View.pid)
      --log-file LOG_FILE  set the path to the log file (default: app_dir/Beanstalkd_View.log)
      --url-file URL_FILE  set the path to the URL file (default: app_dir/Beanstalkd_View.url)

Common options:
  -h, --help               Show this message
      --version            Show version
```
