### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by JerryGreen** [denniskuczynski/beanstalkd_view#35]
so I'm using `bundle exec beanstalkd_view`

and I get this error:

```
/Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/backports-2.8.2/lib/backports/1.8.7/fixnum.rb:1: warning: constant ::Fixnum is deprecated
/Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/backports-2.8.2/lib/backports/1.8.7/float.rb:1: warning: constant ::Fixnum is deprecated
[2018-06-06 19:05:55 +0500] Starting 'Beanstalkd View'...
[2018-06-06 19:05:55 +0500] trying port 5678...
Traceback (most recent call last):
	24: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	23: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	22: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/bin/beanstalkd_view:23:in `<main>'
	21: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/bin/beanstalkd_view:23:in `load'
	20: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/beanstalkd_view-2.0.0/bin/beanstalkd_view:15:in `<top (required)>'
	19: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/beanstalkd_view-2.0.0/bin/beanstalkd_view:15:in `new'
	18: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/vegas-0.1.11/lib/vegas/runner.rb:77:in `initialize'
	17: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/vegas-0.1.11/lib/vegas/runner.rb:109:in `start'
	16: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/vegas-0.1.11/lib/vegas/runner.rb:132:in `find_port'
	15: from /Users/jerrygreen/.rvm/gems/ruby-2.5.0/gems/vegas-0.1.11/lib/vegas/runner.rb:146:in `port_open?'
	14: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:35:in `open'
	13: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:735:in `open'
	12: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
	11: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
	10: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
	 9: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
	 8: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
	 7: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
	 6: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 5: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 4: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	 3: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	 2: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 1: from /Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/Users/jerrygreen/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to 0.0.0.0:5678 (undefined method `[]' for nil:NilClass) (NoMethodError)
```

I'm not sure where's the problem. I tried other ports, same error.
is this intended to use with rails api?
Maybe 2.5.0 ruby not supported?
Any suggestions?

**Comment by kofronpi** [comment]
This project does not seem to be maintained, ruby 2.5.0 might be a tad too recent..
